/**
 * Dispatch table from `configSettingType` → {@link ResourceGenerator}.
 *
 * The synth pipeline (HOM-59) walks a validated `qpq.config.json` settings list
 * and routes each setting to the generator registered here. Settings without a
 * registered generator are either translator-only (consumed elsewhere — see
 * ARCHITECTURE.md §2.4) or owned by a sibling ticket (HOM-58 wires the
 * webserver-layer generators into the same registry).
 */

import { awsAlarmGenerator } from './awsAlarm';
import { eventBusGenerator } from './eventBus';
import { graphDatabaseGenerator } from './graphDatabase';
import { keyValueStoreGenerator } from './keyValueStore';
import { notifyErrorGenerator } from './notifyError';
import { parameterGenerator } from './parameter';
import { queueGenerator } from './queue';
import { secretGenerator } from './secret';
import { storageDriveGenerator } from './storageDrive';
import { ResourceGenerator } from './types';
import { userDirectoryGenerator } from './userDirectory';
import { WEBSERVER_RESOURCE_GENERATORS } from './webserver';

/** All core generators registered by HOM-57. */
export const CORE_RESOURCE_GENERATORS: readonly ResourceGenerator[] = [
  keyValueStoreGenerator,
  storageDriveGenerator,
  queueGenerator,
  eventBusGenerator,
  secretGenerator,
  parameterGenerator,
  userDirectoryGenerator,
  graphDatabaseGenerator,
  notifyErrorGenerator,
  awsAlarmGenerator,
];

/**
 * Core + webserver generators, in a single dispatch-ready list. The synth
 * pipeline (HOM-59) feeds this into {@link buildResourceGeneratorRegistry}
 * to walk a full `qpq.config.json` without having to know about the
 * core/webserver split.
 */
export const ALL_RESOURCE_GENERATORS: readonly ResourceGenerator[] = [
  ...CORE_RESOURCE_GENERATORS,
  ...WEBSERVER_RESOURCE_GENERATORS,
];

/**
 * Setting types that are intentionally not generated by this layer. Listed so
 * the synth pipeline can decide between "skip silently" and "error on unknown".
 * Mirrors ARCHITECTURE.md §2.4.
 */
export const TRANSLATOR_ONLY_SETTING_TYPES: readonly string[] = [
  '@quidproquo-core/config/AppName',
  '@quidproquo-core/config/moduleName',
  '@quidproquo-core/config/apiBuildPath',
  '@quidproquo-core/config/actionProcessors',
  '@quidproquo-core/config/EnvironmentSettings',
  '@quidproquo-core/config/global',
  '@quidproquo-core/config/ConfigValue',
  '@quidproquo-core/config/Ai',
  '@quidproquo-core/config/ClaudeAi',
  '@quidproquo-aws/config/AwsServiceAccountInfo',
  '@quidproquo-aws/config/awsDyanmoOverrideForKvs',
  '@quidproquo-aws/config/bootstrapAwsOrganization',
];

export type ResourceGeneratorRegistry = Map<string, ResourceGenerator>;

/** Build a `Map` indexed by `configSettingType` from a list of generators. */
export const buildResourceGeneratorRegistry = (
  generators: readonly ResourceGenerator[] = CORE_RESOURCE_GENERATORS,
): ResourceGeneratorRegistry => {
  const registry: ResourceGeneratorRegistry = new Map();
  for (const generator of generators) {
    if (registry.has(generator.configSettingType)) {
      throw new Error(
        `Duplicate ResourceGenerator registered for configSettingType "${generator.configSettingType}".`,
      );
    }
    registry.set(generator.configSettingType, generator);
  }
  return registry;
};

/** Whether `configSettingType` is consumed by the translator without producing a module. */
export const isTranslatorOnlySettingType = (configSettingType: string): boolean =>
  TRANSLATOR_ONLY_SETTING_TYPES.includes(configSettingType);
