/**
 * ServiceFunction (`@quidproquo-webserver/config/ServiceFunction`) →
 * `service-function` module.
 *
 * CDK parity: `QpqWebserverServiceFunctionConstruct` — an `aws_lambda_function`
 * plus its log group + execution role. The IAM grants the function actually
 * needs are inferred from the story dependency graph; HOM-23 wires those.
 * Lambda artefact wiring (`s3_bucket`, `s3_key`, `source_code_hash`) is
 * delegated to terraform variables generated by HOM-61 — the generator emits
 * references like `var.<label>_artifact_s3_bucket` so the build pipeline can
 * populate them without re-running synth.
 */

import { attrs, moduleBlock, ref } from '../../hcl';
import { QpqConfigSettingJson } from '../../synth/types';
import { buildModuleLabel, resolveQpqRuntimeResourceName } from '../naming';
import { GeneratedResource, GeneratorContext, ResourceGenerator } from '../types';
import { readOwner, readString } from '../util';
import { WEBSERVER_SETTING_TYPE } from './settingTypes';

const MODULE_LOGICAL_NAME = 'service-function';
const MODULE_LABEL_PREFIX = 'service_function';
const QPQ_RESOURCE_TYPE_SUFFIX = 'sfunc';

export const serviceFunctionGenerator: ResourceGenerator = {
  configSettingType: WEBSERVER_SETTING_TYPE.ServiceFunction,

  generate(setting: QpqConfigSettingJson, ctx: GeneratorContext): GeneratedResource[] {
    const functionName = readString(setting, 'functionName') ?? setting.uniqueKey;
    const label = buildModuleLabel(MODULE_LABEL_PREFIX, setting.uniqueKey);

    const resolvedName = resolveQpqRuntimeResourceName(
      functionName,
      QPQ_RESOURCE_TYPE_SUFFIX,
      ctx.resolved,
      readOwner(setting),
    );

    const block = moduleBlock({
      name: label,
      source: ctx.moduleSource(MODULE_LOGICAL_NAME),
      attributes: attrs({
        function_name: resolvedName,
        qpq_function_name: functionName,
        runtime: setting.runtime ?? null,
        virtual_network_name: readString(setting, 'virtualNetworkName'),
        s3_bucket: ref(`var.${label}_artifact_s3_bucket`),
        s3_key: ref(`var.${label}_artifact_s3_key`),
        source_code_hash: ref(`var.${label}_artifact_source_code_hash`),
        tags: {
          application: ctx.resolved.applicationName,
          module: ctx.resolved.moduleName,
          environment: ctx.resolved.environment,
          qpq_setting_type: 'serviceFunction',
          qpq_unique_key: setting.uniqueKey,
        },
      }),
    });

    return [{ stack: 'api', blocks: [block] }];
  },
};
